; acl4SSR 精简极简版

; ====== 策略组定义 ======
custom_proxy_group=🚀 规则类型`select`[]♻️ 自动选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=☑️ 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`https://www.google.com/generate_204`600,,50
custom_proxy_group=🤖 Ai平台`select`[]🚀 规则类型`[]☑️ 手动切换`[]♻️ 自动选择`.*
custom_proxy_group=🛡️ CF-验证`select`[]☑️ 手动切换`[]🚀 规则类型`[]DIRECT`.*
custom_proxy_group=📲 Telegram`select`[]🚀 规则类型`[]☑️ 手动切换`[]♻️ 自动选择`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 规则类型
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 规则类型`[]🎯 全球直连

; ====== 核心分流规则 ======
ruleset=🛡️ CF-验证,[]DOMAIN-SUFFIX,challenges.cloudflare.com
ruleset=🛡️ CF-验证,[]DOMAIN-SUFFIX,captcha.website
ruleset=🛡️ CF-验证,[]DOMAIN-SUFFIX,a.nel.cloudflare.com

; ====== 2. 基础直连规则 ======
ruleset=🎯 全球直连,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Download.list

; ====== 3. Google Play 核心规则 ======
ruleset=🚀 规则类型,[]DOMAIN-SUFFIX,services.googleapis.cn

; ====== 4. AI 服务专属规则 ======
ruleset=🤖 Ai平台,https://raw.githubusercontent.com/bilibili2077/ACL4SSR/refs/heads/main/AiDomain

; ====== 5. 其他直连规则 ======
ruleset=🎯 全球直连,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/ChinaCompanyIp.list

; ====== 6. Google 推送（FCM） ======
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list

; ====== 7. 常用代理规则 ======
ruleset=📲 Telegram,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Telegram.list
ruleset=🚀 规则类型,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 规则类型,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 规则类型,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list

; ====== 8. GEOIP 与兜底匹配 ======
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

enable_rule_generator=true
overwrite_original_rules=true
